plugins:
    - jekyll-seo-tag
    - jekyll-scholar
    - jekyll-redirect-from
    - jekyll-scholar

title: Andrew Lee
author: GitHub User
email: ajyl@umich.edu
description: > # this means to ignore newlines until "show_exerpts:"
  Personal website for Andrew Lee
show_excerpts: true # set to true to show excerpts on the homepage

basedir: "_pages"

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Andrew Lee
  tagline: About Me
  date_format: "%b %-d, %Y"
  sitemap: false # set to true to generate sitemap.xml content
  search: false # set to true to enable searchbar
  dark_mode: false # set to true to add dark mode toggle
  portfolio_image: "assets/prof_pic.jpg" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    #- home
    - page
    - post
  navigation:
    - title: About
      url: "/about"
    - title: Publications
      url: "/publications"
    - title: Blog
      url: "/blog"
  # Hard coding CV in _layouts/default.html
    #- title: CV
    #  url: "/cv"
  # generate social links in footer
  social_links:
    googlescholar: oQiCjnwAAAAJ
    twitter: a_jy_l
    github: ajyl
    email: ajyl@umich.edu


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite
remote_theme: samarsault/plainwhite-jekyll

include: ["_pages"]

scholar:
  last_name: [Lee]
  first_name: [Andrew]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true
  bibtex_filters:

